/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.earthtime.visualizationUtilities;

/**
 *
 * @author samuelbowring
 */
public class ProgressBarViewer extends javax.swing.JFrame {

    /**
     * Creates new form ProgressBarViewer
     */
    public ProgressBarViewer () {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main ( String args[] ) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ( "Nimbus".equals( info.getName() ) ) {
//                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger( ProgressBarViewer.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger( ProgressBarViewer.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger( ProgressBarViewer.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger( ProgressBarViewer.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater( new Runnable() {
//            public void run () {
//                new ProgressBarViewer().setVisible( true );
//            }
//        } );
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
