/*
 * SampleDateInterpretationAny2VariablesChooser.java
 *
 *
 * Copyright 2006-2015 James F. Bowring and www.Earth-Time.org
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.earthtime.UPb_Redux.dialogs.sampleManagers.sampleDateInterpretationManagers;

import java.util.Vector;
import org.earthtime.beans.ET_JButton;
import org.earthtime.dialogs.DialogEditor;
import org.earthtime.plots.anyTwo.PlotAny2Panel;

/**
 *
 * @author James F. Bowring
 */
public class SampleDateInterpretationAny2VariablesChooser extends DialogEditor {

    // Fields
    private final PlotAny2Panel plotAny2Panel;

    /**
     * Creates new form SampleDateInterpretationChooserDialog
     *
     * @param parent
     * @param modal
     * @param plotAny2Panel the value of plotAny2Panel
     * @param variablesList
     */
    public SampleDateInterpretationAny2VariablesChooser(//
            java.awt.Frame parent, boolean modal, PlotAny2Panel plotAny2Panel, Vector<String> variablesList) {
        super(parent, modal);

        this.plotAny2Panel = plotAny2Panel;

        initComponents();

        xVariablesList.setListData(variablesList);
        xVariablesList.setSelectedValue(plotAny2Panel.getNameOfXaxisSourceValueModel(), true);
        yVariablesList.setListData((Vector<String>) variablesList.clone());
        yVariablesList.setSelectedValue(plotAny2Panel.getNameOfYaxisSourceValueModel(), true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xVariable_scrollPane = new javax.swing.JScrollPane();
        xVariablesList = new javax.swing.JList<>();
        buttonsPanel = new javax.swing.JPanel();
        ok_button = new ET_JButton();
        chooseTracer_label = new javax.swing.JLabel();
        yVariable_scrollPane = new javax.swing.JScrollPane();
        yVariablesList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Available Variables");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(245, 236, 206));
        setForeground(java.awt.Color.white);
        setName(getTitle());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xVariablesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        xVariablesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xVariablesListMouseClicked(evt);
            }
        });
        xVariable_scrollPane.setViewportView(xVariablesList);

        getContentPane().add(xVariable_scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 22, 240, 370));

        buttonsPanel.setBackground(new java.awt.Color(252, 236, 235));
        buttonsPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        buttonsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ok_button.setBackground(new java.awt.Color(255, 255, 255));
        ok_button.setForeground(new java.awt.Color(255, 51, 0));
        ok_button.setText("OK");
        ok_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ok_button.setMargin(new java.awt.Insets(0, 1, 0, 1));
        ok_button.setOpaque(true);
        ok_button.setPreferredSize(new java.awt.Dimension(140, 23));
        ok_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_buttonActionPerformed(evt);
            }
        });
        buttonsPanel.add(ok_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 2, 480, 30));

        getContentPane().add(buttonsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 560, -1));

        chooseTracer_label.setBackground(new java.awt.Color(255, 255, 255));
        chooseTracer_label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        chooseTracer_label.setText("Available variables: choose X and Y:   BETA TEST ONLY");
        chooseTracer_label.setOpaque(true);
        getContentPane().add(chooseTracer_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 380, -1));

        yVariablesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        yVariablesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yVariablesListMouseClicked(evt);
            }
        });
        yVariable_scrollPane.setViewportView(yVariablesList);

        getContentPane().add(yVariable_scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 22, 240, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ok_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_buttonActionPerformed
        OK();
        close();
    }//GEN-LAST:event_ok_buttonActionPerformed

    private void xVariablesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xVariablesListMouseClicked
//        if (evt.getClickCount() == 2) {
//            OK();
//            close();
//        }
}//GEN-LAST:event_xVariablesListMouseClicked

    private void yVariablesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yVariablesListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_yVariablesListMouseClicked

    private void OK() {
        if ((xVariablesList.getSelectedValuesList().size() > 0) && (xVariablesList.getSelectedValuesList().size() > 0)) {
            plotAny2Panel.setNameOfXaxisSourceValueModel(xVariablesList.getSelectedValue());
            plotAny2Panel.setNameOfYaxisSourceValueModel(yVariablesList.getSelectedValue());
        }

        close();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JLabel chooseTracer_label;
    private javax.swing.JButton ok_button;
    private javax.swing.JScrollPane xVariable_scrollPane;
    private javax.swing.JList<String> xVariablesList;
    private javax.swing.JScrollPane yVariable_scrollPane;
    private javax.swing.JList<String> yVariablesList;
    // End of variables declaration//GEN-END:variables

}
