/*
 * Copyright 2006-2016 CIRDLES.org.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.earthtime.Tripoli.dataViews.rawDataReviews;

import java.awt.Color;
import java.awt.Rectangle;
import java.util.Map;
import javax.swing.JLayeredPane;
import org.earthtime.Tripoli.dataModels.DataModelInterface;
import org.earthtime.Tripoli.dataViews.AbstractRawDataView;
import org.earthtime.Tripoli.massSpecSetups.AbstractMassSpecSetup;
import org.earthtime.dialogs.DialogEditor;
import org.earthtime.isotopes.IsotopesEnum;

/**
 *
 * @author James F. Bowring <bowring at gmail.com>
 */
public class TimeResolvedAnalysisDataView extends DialogEditor {

    private static int SESSION_VIEW_WIDTH = 12000;
    private JLayeredPane rawDataSession;
    private AbstractRawDataView[] rawDataSessionPlots;
    private AbstractMassSpecSetup massSpec;

    /**
     * Creates new form TimeResolvedAnalysisDataView
     *
     * @param parent
     * @param modal
     * @param massSpec
     */
    public TimeResolvedAnalysisDataView(java.awt.Frame parent, boolean modal, AbstractMassSpecSetup massSpec) {
        super(parent, modal);
        this.massSpec = massSpec;
        initComponents();
        rawDataSessionPlotScrollPane.getHorizontalScrollBar().setUnitIncrement(100);

//        rawDataSessionPlotScrollPane.getViewport().setScrollMode(JViewport.BLIT_SCROLL_MODE);

        rawDataSessionPlotScrollPane.getViewport().putClientProperty("EnableWindowBlit", Boolean.TRUE);

        initSession();
    }

    private void initSession() {
        setSize(1200, 750);
        rawDataSession = new JLayeredPane();
        rawDataSession.setBounds(0, 0, SESSION_VIEW_WIDTH, rawDataSessionPlotScrollPane.getHeight() - 25);
        // this forces scroll bar
        rawDataSession.setPreferredSize(rawDataSession.getSize());
        rawDataSession.setOpaque(true);
        rawDataSession.setBackground(Color.white);
        rawDataSessionPlotScrollPane.setViewportView(rawDataSession);
        rawDataSessionPlotScrollPane.revalidate();

        Map<IsotopesEnum, DataModelInterface> isotopeToRawIntensitiesMap = massSpec.getIsotopeMappingModel().getIsotopeToRawIntensitiesMap();
        rawDataSessionPlots = new AbstractRawDataView[isotopeToRawIntensitiesMap.size()];
        isotopeToRawIntensitiesMap.forEach((isotope, dataModel) -> {
            int index = massSpec.getVirtualCollectorModelMapToFieldIndexes().get(dataModel);
            rawDataSessionPlots[index] = new RawDataSessionPlot(dataModel, new Rectangle(0, index * 100 + 10, 12000, 100));
            rawDataSession.add(rawDataSessionPlots[index], JLayeredPane.DEFAULT_LAYER);
            rawDataSessionPlots[index].preparePanel(true, false);
            rawDataSessionPlots[index].repaint();
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        rawDataSessionPlotScrollPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 750));

        jLayeredPane2.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane2.setOpaque(true);

        rawDataSessionPlotScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        jLayeredPane2.setLayer(rawDataSessionPlotScrollPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(rawDataSessionPlotScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1034, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(rawDataSessionPlotScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane rawDataSessionPlotScrollPane;
    // End of variables declaration//GEN-END:variables
}
