/*
 * EarthTimeTracerDialog.java
 *
 *
 * Copyright 2006-2018 James F. Bowring, CIRDLES.org, and Earth-Time.org
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.earthtime.dialogs;

import org.earthtime.dialogs.DialogEditor;

/**
 *
 * @author  James F. Bowring
 */
public class EarthTimeTracerDialog extends DialogEditor {
    
    // Fields
    private String[] tracerList;
    private String selectedTracerName;
    
    /** Creates new form EarthTimeTracerDialog
     * @param parent
     * @param modal
     * @param tracerList  
     */
    public EarthTimeTracerDialog
            (java.awt.Frame parent, 
            boolean modal,
            String[] tracerList) {
        super(parent, modal);
        
        setLocationRelativeTo(parent);
        setTracerList(tracerList);
        setSelectedTracerName("");
        
        initComponents();
        
        tracers_list.setListData(tracerList);

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tracers_scrollPane = new javax.swing.JScrollPane();
        tracers_list = new javax.swing.JList<String>();
        buttonsPanel = new javax.swing.JPanel();
        save_button = new javax.swing.JButton();
        close_button = new javax.swing.JButton();
        chooseTracer_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Current Tracers from Earth-Time.org");
        setResizable(false);

        tracers_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tracers_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tracers_listMouseClicked(evt);
            }
        });
        tracers_scrollPane.setViewportView(tracers_list);

        buttonsPanel.setBackground(new java.awt.Color(252, 236, 235));
        buttonsPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        save_button.setForeground(new java.awt.Color(255, 51, 0));
        save_button.setText("OK");
        save_button.setMargin(new java.awt.Insets(0, 1, 0, 1));
        save_button.setPreferredSize(new java.awt.Dimension(140, 23));
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        close_button.setForeground(new java.awt.Color(255, 51, 0));
        close_button.setText("Cancel");
        close_button.setMargin(new java.awt.Insets(0, 1, 0, 1));
        close_button.setPreferredSize(new java.awt.Dimension(140, 23));
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout buttonsPanelLayout = new org.jdesktop.layout.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(buttonsPanelLayout.createSequentialGroup()
                .add(17, 17, 17)
                .add(save_button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 80, Short.MAX_VALUE)
                .add(close_button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(buttonsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(save_button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(close_button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        chooseTracer_label.setText("Choose a tracer to import from Earth-Time.org:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(buttonsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(55, 55, 55)
                .add(tracers_scrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 238, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(chooseTracer_label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(chooseTracer_label)
                .add(26, 26, 26)
                .add(tracers_scrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 73, Short.MAX_VALUE)
                .add(buttonsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        close();
    }//GEN-LAST:event_close_buttonActionPerformed

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        OK();
        close();
    }//GEN-LAST:event_save_buttonActionPerformed

    private void tracers_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tracers_listMouseClicked
        if (evt.getClickCount() == 2){
            OK();
            close();
        }
    }//GEN-LAST:event_tracers_listMouseClicked
    
    private void OK(){
        if (tracers_list.getSelectedIndex() > -1)
            setSelectedTracerName((String)tracers_list.getSelectedValue());
    }

    /**
     * 
     * @return
     */
    public String[] getTracerList() {
        return tracerList;
    }

    /**
     * 
     * @param tracerList
     */
    public void setTracerList(String[] tracerList) {
        this.tracerList = tracerList;
    }

    /**
     * 
     * @return
     */
    public String getSelectedTracerName() {
        return selectedTracerName;
    }

    /**
     * 
     * @param selectedTracerName
     */
    public void setSelectedTracerName(String selectedTracerName) {
        this.selectedTracerName = selectedTracerName;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JLabel chooseTracer_label;
    private javax.swing.JButton close_button;
    private javax.swing.JButton save_button;
    private javax.swing.JList<String> tracers_list;
    private javax.swing.JScrollPane tracers_scrollPane;
    // End of variables declaration//GEN-END:variables
    
}
